# -*- coding: utf-8 -*-
# Generated by Django 1.11.25 on 2019-10-26 09:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0010_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='student_only',
        ),
    ]
