# Generated by Django 2.2.7 on 2019-11-08 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_auto_20191026_0930'),
        ('course', '0012_auto_20191108_1447'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='participants',
            field=models.ManyToManyField(blank=True, through='course.Participation', to='user.UserInformation'),
        ),
    ]
