# Generated by Django 2.2.16 on 2020-09-06 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0013_course_participants'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='author',
            field=models.CharField(default='Anonymous', max_length=301),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='news',
            name='modified',
            field=models.DateField(auto_now=True),
        ),
    ]
