# Generated by Django 2.2.16 on 2020-09-08 22:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0014_auto_20200906_1739'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Description',
        ),
    ]
