# -*- coding: utf-8 -*-
# Generated by Django 1.11.25 on 2019-10-25 17:34
from __future__ import unicode_literals

from django.db import migrations, models
import user.models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_userinformation_accepted_privacy_policy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinformation',
            name='accepted_privacy_policy',
            field=models.BooleanField(validators=[user.models.privacy_policy_consented]),
        ),
    ]
