# -*- coding: utf-8 -*-
# Generated by Django 1.11.25 on 2019-10-26 09:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0011_remove_course_student_only'),
        ('user', '0003_auto_20191025_1734'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentinformation',
            name='faculty',
        ),
        migrations.RemoveField(
            model_name='studentinformation',
            name='userinformation_ptr',
        ),
        migrations.AlterField(
            model_name='activation',
            name='type',
            field=models.CharField(choices=[('e', 'email')], max_length=1),
        ),
        migrations.DeleteModel(
            name='Faculty',
        ),
        migrations.DeleteModel(
            name='StudentInformation',
        ),
    ]
